#!/bin/bash
#
# Copyright (c) 2018 Dell Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT
# LIMITATION ANY IMPLIED WARRANTIES OR CONDITIONS OF TITLE, FITNESS
# FOR A PARTICULAR PURPOSE, MERCHANTABLITY OR NON-INFRINGEMENT.
#
# See the Apache Version 2.0 License for specific language governing
# permissions and limitations under the License.
#


function usage ()
{
        echo "usage: $0 [ --entity-type [ psu | fantray | card ] ] [ --slot <slot> ] <led-name> [ on | off ]"
        exit 1
}

ENTITY_TYPE=""
if [ $# -ge 2 -a "$1" = --entity-type ]
then
        case "$2" in
        [Pp][Ss][Uu])
                ENTITY_TYPE="entity-type=1"
                ;;
        [Ff][Aa][Nn][Tt][Rr][Aa][Yy])
                ENTITY_TYPE="entity-type=2"
                ;;
        [Cc][Aa][Rr][Dd])
                ENTITY_TYPE="entity-type=3"
                ;;
        *)
                usage
                ;;
        esac
        shift 2
fi

SLOT=""
if [ $# -ge 2 -a "$1" = --slot ]
then
        SLOT="slot=$2"
        shift 2
fi

if [ $# -lt 1 ]
then
        usage
fi

LEDNAME=$1
shift

if [ $# -lt 1 ]
then
        usage
fi

case "$1" in
[Oo][Nn])
        ONOFF=1
        ;;
[Oo][Ff][Ff])
        ONOFF=0
        ;;
*)
        usage
        ;;
esac
shift

if [ $# -ne 0 ]
then
        usage
fi

cps_set_oid.py -oper set base-pas/led $ENTITY_TYPE $SLOT name=$LEDNAME on=$ONOFF
